name: Run Playwright

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0-14/2 * * *' # 9:00 - 23:00
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    environment:
      name: Config
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install Yarn
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Build index.ts
        run: yarn build

      - name: Run index.js
        run: node dist/src/index.js
